### PR TITLE
@RxLogSubscriber crashes with NullPointerException

### LINKED ISSUE #14: @RxLogSubscriber NullPointerException
There are a few problems with a library dude which I will try to solve and send a PR. I found that if send an empty observable back or a null value back then the RxLogSubscriber crashes with NullPointerException. If I removed it then the subscriber works normally.

### PR DESCRIPTION
**Pull request by spirosoik**
Fixed #14. The @RxLogSubscriber crashes with NullPointerException when the param values are empty eg. ```Observable.just(null)```

### CODE REVIEW

**Comment by spirosoik** [comment]
@android10 please review. Any thoughts ideas for a better approach than this?

**Comment by android10** [comment]
@spirosoik I will review it by the end of the week so we can generate another version asap :)

**Comment by spirosoik** [comment]
ok dude @android10

File: frodo-runtime/src/main/java/com/fernandocejas/frodo/aspect/LogSubscriber.java [hunk 1]
```diff
@@ -78,9 +80,14 @@ public void beforeOnStartExecution(JoinPoint joinPoint) {
   public void beforeOnNextExecution(JoinPoint joinPoint) {
     countAndMeasureTime();
     final FrodoJoinPoint frodoJoinPoint = new FrodoJoinPoint(joinPoint);
-    final Object value = frodoJoinPoint.getMethodParamValuesList().get(0);
-    messageManager.printSubscriberOnNext(joinPoint.getTarget().getClass().getSimpleName(),
-        value.toString(),
+    final String message;
```
Comment (android10) [inline frodo-runtime/src/main/java/com/fernandocejas/frodo/aspect/LogSubscriber.java]: It is not this class responsibility to build the message. This logic should sit on ```MessageManager.class```. It might be a good idea to pass in the value as it is: ```Object.class``` and handle the ```null``` case inside ```printSubscriberOnNext()``` method.

File: frodo-runtime/src/main/java/com/fernandocejas/frodo/joinpoint/FrodoJoinPoint.java [hunk 2]
```diff
@@ -47,7 +47,9 @@ public FrodoJoinPoint(JoinPoint joinPoint) {
     this.methodName = this.methodSignature.getName();
     this.methodParamTypesList = Arrays.asList(this.methodSignature.getParameterTypes());
     this.methodParamNamesList = Arrays.asList(this.methodSignature.getParameterNames());
-    this.methodParamValuesList = Arrays.asList(this.joinPoint.getArgs());
+    this.methodParamValuesList =
```
Comment (android10) [inline frodo-runtime/src/main/java/com/fernandocejas/frodo/joinpoint/FrodoJoinPoint.java]: Same could be applied to in order to be more defensive:
```java
  public FrodoJoinPoint(JoinPoint joinPoint) {
    if (joinPoint == null) {
      throw new IllegalArgumentException("Constructor parameters cannot be null!!!");
    }

    this.joinPoint = joinPoint;
    this.methodSignature = (MethodSignature) this.joinPoint.getSignature();
    this.classCanonicalName = this.methodSignature.getDeclaringType().getCanonicalName();
    this.classSimpleName = this.methodSignature.getDeclaringType().getSimpleName();
    this.methodName = this.methodSignature.getName();
    this.executionThreadName = Thread.currentThread().getName();
    this.joinPointUniqueName = this.generateJoinPointUniqueName();
    final Class[] parameterTypes = this.methodSignature.getParameterTypes();
    final String[] parameterNames = this.methodSignature.getParameterNames();
    final Object[] args = this.joinPoint.getArgs();
    this.methodParamTypesList = parameterTypes != null ?
        Arrays.asList(parameterTypes) : Collections.<Class>emptyList();
    this.methodParamNamesList = parameterNames != null ?
        Arrays.asList(parameterNames) : Collections.<String>emptyList();
    this.methodParamValuesList = args != null ? Arrays.asList(args) : Collections.emptyList();
  }
```

File: frodo-runtime/src/test/java/com/fernandocejas/frodo/aspect/LogSubscriberTest.java [hunk 3]
```diff
@@ -89,6 +89,19 @@ public void printOnNextMessageBeforeSubscriberOnNextExecution() {
         eq("value"), anyString());
   }
 
+  @Test public void printOnNextMessageBeforeSubscriberOnNextExecutionWithEmptyValues() {
```
Comment (android10) [inline frodo-runtime/src/test/java/com/fernandocejas/frodo/aspect/LogSubscriberTest.java]: Test should be written in MessageManager class by passing a null value an asserting its message.

**Comment by android10** [comment]
There are a few comments. We are more error prone with this PR but I still think that sending a null value in an observable it does not make too much sense. In my production code I would use wrap my value in an ```Optional.class```

**Comment by android10** [comment]
By the way I added more samples to reproduce the problem and by using ```Observable.just(null)``` works well:

```
D  Frodo => [@Observable#doNothing -> onSubscribe()]
D  Frodo => [@Observable#doNothing -> onCompleted()]
D  Frodo => [@Observable#doNothing -> onTerminate()]
D  Frodo => [@Observable#doNothing -> @Emitted -> 0 elements :: @Time -> 0 ms]
D  Frodo => [@Observable#doNothing ->  :: @ObserveOn -> main]
D  Frodo => [@Observable#doNothing -> onUnsubscribe()]                        

D  Frodo => [@Observable#doSomething -> onSubscribe()]
D  Frodo => [@Observable#doSomething -> onNext() -> null]
D  Frodo => [@Observable#doSomething -> onCompleted()]
D  Frodo => [@Observable#doSomething -> onTerminate()]
D  Frodo => [@Observable#doSomething -> @Emitted -> 1 element :: @Time -> 0 ms]
D  Frodo => [@Observable#doSomething -> @SubscribeOn -> RxNewThreadScheduler-5 :: @ObserveOn -> main]
D  Frodo => [@Observable#doSomething -> onUnsubscribe()]                        

D  Frodo => [@Observable#sendNull -> onSubscribe()]
D  Frodo => [@Observable#sendNull -> onNext() -> null]
D  Frodo => [@Observable#sendNull -> onCompleted()]
D  Frodo => [@Observable#sendNull -> onTerminate()]
D  Frodo => [@Observable#sendNull -> @Emitted -> 1 element :: @Time -> 0 ms]
D  Frodo => [@Observable#sendNull -> @SubscribeOn -> RxNewThreadScheduler-6 :: @ObserveOn -> main]
D  Frodo => [@Observable#sendNull -> onUnsubscribe()]
```

Here is the commit: https://github.com/android10/frodo/commit/e281739cea7577d8143858b371627252535f4808

File: frodo-runtime/src/main/java/com/fernandocejas/frodo/aspect/LogSubscriber.java (hunk 1 above)
Comment (spirosoik) [inline frodo-runtime/src/main/java/com/fernandocejas/frodo/aspect/LogSubscriber.java]: I haven't seen `MessageManager.class`.  Yes because we are encapsulating the handling on `printSubscriberOnNext`

File: frodo-runtime/src/main/java/com/fernandocejas/frodo/joinpoint/FrodoJoinPoint.java (hunk 2 above)
Comment (spirosoik) [inline frodo-runtime/src/main/java/com/fernandocejas/frodo/joinpoint/FrodoJoinPoint.java]: Yes this is true.

File: frodo-runtime/src/test/java/com/fernandocejas/frodo/aspect/LogSubscriberTest.java (hunk 3 above)
Comment (spirosoik) [inline frodo-runtime/src/test/java/com/fernandocejas/frodo/aspect/LogSubscriberTest.java]: :+1:

**Comment by spirosoik** [comment]
@android10 Sometimes the crowd does not use Java8 so to be completely defensive we must be sure that if we got a null value the library will work without a problem. 

Also, If you try my test case without the fixes you'll see that the error occurred.

**Comment by android10** [comment]
@spirosoik your argument makes sense. Let's be defensive here. Looking forward for the changes so I merge it :)

File: frodo-runtime/src/main/java/com/fernandocejas/frodo/aspect/LogSubscriber.java (hunk 1 above)
Comment (spirosoik) [inline frodo-runtime/src/main/java/com/fernandocejas/frodo/aspect/LogSubscriber.java]: @android10 So you suggest to pass the whole object list `frodoJoinPoint.getMethodParamValuesList()` in the method. I am saying that because if we don't pass it and keep the logic `Object value = frodoJoinPoint.getMethodParamValuesList().get(0)` then we are going to have another exception `ArrayIndexOutOfBoundsException`

**Comment by spirosoik** [comment]
> By the way I added more samples to reproduce the problem, and by using Observable.just(null) works well:

Check that is going to `onError` because of the exception of the Null pointer.

**Comment by spirosoik** [comment]
@android10 review dude!

**Comment by android10** [comment]
@spirosoik nice! Great job!
I'm gonna merge this although I might refactor a little bit the usage of nulls in favor of optionals :)

**Comment by spirosoik** [comment]
:+1: thanks dude.
